export const projects = [
  {
    name: 'BioData Catalyst',
    id: 'bdc',
    imagePath: '/images/bdc.png',
    url: 'https://biodatacatalyst.nhlbi.nih.gov/',
    tags: ['React', 'Gatsby', 'AWS', 'Data Visualization', 'HTML', 'CSS', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'CTMD',
    id: 'ctmd',
    imagePath: '/images/ctmd.png',
    url: 'https://ctmd.renci.org/',
    tags: ['React', 'Node', 'Express', 'Docker', 'PostgreSQL', 'Data Visualization', 'HTML', 'CSS', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'RENCI\'S COVID-19 Response',
    id: 'covid',
    imagePath: '/images/covid.png',
    url: 'https://covid-19.renci.org/',
    tags: ['React', 'Gatsby', 'M↓', 'HTML', 'CSS', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'Create RENCI App',
    id: 'cra',
    imagePath: '/images/cra.png',
    url: 'https://www.npmjs.com/package/@renci/create-renci-app',
    tags: ['React', 'Webpack', 'Babel', 'HTML', 'CSS', 'SCSS', 'PostCSS', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'FABRIC Testbed',
    id: 'fabric',
    imagePath: '/images/fabric.png',
    url: 'https://fabric-testbed.net/',
    tags: ['React', 'Gatsby', 'M↓', 'YAML', 'HTML', 'CSS', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'HeLx UI',
    id: 'helx',
    imagePath: '/images/helx.png',
    url: 'https://heal-dev.blackbalsam-cluster.edc.renci.org/helx/',
    tags: ['React', 'Django', 'HTML', 'CSS', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'Hey, OK! Pictures',
    id: 'heyok',
    imagePath: '/images/hey-ok.png',
    url: 'https://heyokpictures.com/',
    tags: ['SquareSpace', 'CSS', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'First Mile to Health',
    id: 'first-mile',
    imagePath: '/images/first-mile.png',
    url: null,
    tags: ['D3' ,'CSS', 'JavaScript'],
  },
  {
    name: 'Michelle Scaraglino',
    id: 'ms',
    imagePath: '/images/ms.png',
    url: 'https://michellescaraglino.com',
    tags: ['React', 'Gatsby', 'HTML', 'CSS', 'M↓', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'Roadway Hazard Finder',
    id: 'rhf',
    imagePath: '/images/rhf.png',
    url: 'https://dotdsi.renci.org/',
    tags: ['React', 'HTML', 'CSS', 'Data Visualization', 'JavaScript'],
    description: `...`,
  },
  {
    name: 'RENCI\'s SC20 Virtual Booth',
    id: 'sc20',
    imagePath: '/images/sc20.png',
    url: 'https://sc.renci.org/',
    tags: ['React', 'Gatsby', 'M↓', 'HTML', 'CSS', 'JavaScript'],
    description: `...`,
  },
]
